version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    container_name: scriptassist-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scriptassist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6
    restart: always
    container_name: scriptassist-cache
    ports:
      - "6379:6379"

volumes:
  pgdata:
